services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-server
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env

    # depends_on:
    #   postgres:
    #     condition: service_healthy

  # postgres:
  #   image: postgres:16-alpine
  #   container_name: rj-brown-db
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=rjbrown
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

# volumes:
#   postgres_data: